#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="usalp-agent"
INSTALL_DIR="/opt/usalp-agent"
CONFIG_DIR="/etc/usalp-agent"
CONFIG_FILE="${CONFIG_DIR}/agent.yaml"
STATE_DIR="/var/lib/usalp-agent"
QUEUE_DIR="${STATE_DIR}/queue"
API_KEY=""
BACKEND_URL=""
ALLOW_INSECURE=false
DO_STATUS=false
DO_UNINSTALL=false

usage() {
  cat <<'EOF'
Usage:
  install.sh --api-key <KEY> --backend-url https://domain [--allow-insecure]
  install.sh --status
  install.sh --uninstall

Options:
  --api-key          Raw server-specific key generated by the dashboard
  --backend-url      Public backend URL, normally https://domain
  --install-dir      Agent runtime directory (default: /opt/usalp-agent)
  --config-file      Agent config path (default: /etc/usalp-agent/agent.yaml)
  --queue-dir        Persistent queue directory (default: /var/lib/usalp-agent/queue)
  --allow-insecure   Permit http:// backend URLs for local development only
EOF
}

info() { echo "[info] $*"; }
warn() { echo "[warn] $*" >&2; }
die() { echo "[error] $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-key) API_KEY="${2:-}"; shift 2 ;;
    --backend-url) BACKEND_URL="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --config-file) CONFIG_FILE="${2:-}"; CONFIG_DIR="$(dirname "$CONFIG_FILE")"; shift 2 ;;
    --queue-dir) QUEUE_DIR="${2:-}"; STATE_DIR="$(dirname "$QUEUE_DIR")"; shift 2 ;;
    --allow-insecure) ALLOW_INSECURE=true; shift ;;
    --status) DO_STATUS=true; shift ;;
    --uninstall) DO_UNINSTALL=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

require_root() {
  [[ ${EUID} -eq 0 ]] || die "Run with root privileges, for example: sudo bash install.sh ..."
}

status_agent() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl status "$SERVICE_NAME" --no-pager || true
  else
    warn "systemctl not found"
  fi
  echo
  echo "Config: ${CONFIG_FILE}"
  echo "Queue:  ${QUEUE_DIR}"
  if [[ -d "$QUEUE_DIR" ]]; then
    echo "Queued payloads: $(find "$QUEUE_DIR" -maxdepth 1 -type f -name '*.json' | wc -l)"
  fi
}

uninstall_agent() {
  require_root
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop "$SERVICE_NAME" >/dev/null 2>&1 || true
    systemctl disable "$SERVICE_NAME" >/dev/null 2>&1 || true
  fi
  rm -f "/etc/systemd/system/${SERVICE_NAME}.service"
  systemctl daemon-reload >/dev/null 2>&1 || true
  rm -rf "$INSTALL_DIR" "$CONFIG_DIR"
  info "Agent uninstalled. Queue data was left in ${STATE_DIR}."
}

if [[ "$DO_STATUS" == "true" ]]; then
  status_agent
  exit 0
fi

if [[ "$DO_UNINSTALL" == "true" ]]; then
  uninstall_agent
  exit 0
fi

require_root

[[ -n "$API_KEY" ]] || die "--api-key is required"
[[ -n "$BACKEND_URL" ]] || die "--backend-url is required"
BACKEND_URL="${BACKEND_URL%/}"

if [[ "$BACKEND_URL" == http://* && "$ALLOW_INSECURE" != "true" ]]; then
  die "Plain HTTP backend URLs are refused. Use HTTPS or pass --allow-insecure for local development."
fi
if [[ "$BACKEND_URL" != https://* && "$BACKEND_URL" != http://* ]]; then
  die "--backend-url must start with https://"
fi

command -v curl >/dev/null 2>&1 || die "curl is required"
command -v tar >/dev/null 2>&1 || die "tar is required"
command -v systemctl >/dev/null 2>&1 || die "systemd/systemctl is required"
command -v python3 >/dev/null 2>&1 || die "python3 is required"

python3 - <<'PY' || die "Python 3.12+ is required"
import sys
raise SystemExit(0 if sys.version_info >= (3, 12) else 1)
PY

python3 -m venv --help >/dev/null 2>&1 || die "python3 venv support is required. Install python3-venv."
curl -fsS --max-time 10 https://example.com >/dev/null || die "Outbound HTTPS check failed"
curl -fsS --max-time 10 "${BACKEND_URL}/health" >/dev/null || die "Backend health check failed: ${BACKEND_URL}/health"

info "Installing Usalp Agent"
info "Backend: ${BACKEND_URL}"

mkdir -p "$INSTALL_DIR" "$CONFIG_DIR" "$QUEUE_DIR"
chmod 700 "$CONFIG_DIR" "$STATE_DIR" "$QUEUE_DIR"
find "$INSTALL_DIR" -mindepth 1 -maxdepth 1 ! -name ".venv" -exec rm -rf {} +

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
if [[ -n "$SCRIPT_DIR" && -f "${SCRIPT_DIR}/main.py" && -f "${SCRIPT_DIR}/pyproject.toml" ]]; then
  info "Copying agent files from local source"
  mkdir -p "${TMP_DIR}/usalp-agent"
  cp -a \
    "${SCRIPT_DIR}/install.sh" \
    "${SCRIPT_DIR}/pyproject.toml" \
    "${SCRIPT_DIR}/main.py" \
    "${SCRIPT_DIR}/config.py" \
    "${SCRIPT_DIR}/models.py" \
    "${SCRIPT_DIR}/collectors" \
    "${SCRIPT_DIR}/readers" \
    "${SCRIPT_DIR}/sender" \
    "${TMP_DIR}/usalp-agent/"
  find "${TMP_DIR}/usalp-agent" \
    \( -name '__pycache__' -o -name '.pytest_cache' -o -name '.ruff_cache' -o -name '*.egg-info' \) \
    -prune -exec rm -rf {} +
  tar -czf "${TMP_DIR}/agent.tar.gz" -C "$TMP_DIR" usalp-agent
else
  info "Downloading agent package"
  curl -fsSL "${BACKEND_URL}/agent.tar.gz" -o "${TMP_DIR}/agent.tar.gz" \
    || die "Agent package download failed"
fi

tar -xzf "${TMP_DIR}/agent.tar.gz" -C "$INSTALL_DIR" --strip-components=1

info "Creating Python virtual environment"
python3 -m venv "${INSTALL_DIR}/.venv"
"${INSTALL_DIR}/.venv/bin/python" -m pip install --upgrade pip setuptools wheel
"${INSTALL_DIR}/.venv/bin/python" -m pip install "$INSTALL_DIR"

HOSTNAME_VAL="$(hostname -f 2>/dev/null || hostname)"

detect_log_files() {
  local os_id=""
  local os_like=""
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    os_id="${ID:-}"
    os_like="${ID_LIKE:-}"
  fi

  case " ${os_id} ${os_like} " in
    *" rhel "*|*" centos "*|*" fedora "*|*" rocky "*|*" almalinux "*)
      cat <<'EOF'
  - path: /var/log/messages
    tail_lines: 100
    min_level: WARNING
  - path: /var/log/secure
    tail_lines: 100
    min_level: WARNING
EOF
      ;;
    *)
      cat <<'EOF'
  - path: /var/log/syslog
    tail_lines: 100
    min_level: WARNING
  - path: /var/log/auth.log
    tail_lines: 100
    min_level: WARNING
EOF
      ;;
  esac

  cat <<'EOF'
  - path: /var/log/nginx/error.log
    tail_lines: 50
    min_level: ERROR
EOF
}

info "Writing config: ${CONFIG_FILE}"
cat > "$CONFIG_FILE" <<EOF
server_id: ${HOSTNAME_VAL}
backend_url: ${BACKEND_URL}
api_key: ${API_KEY}

intervals:
  fast: 30
  slow: 60

queue:
  dir: ${QUEUE_DIR}
  max_items: 1000
  flush_batch_size: 25

services:
  - nginx
  - docker
  - postgresql
  - redis
  - mysql
  - ssh

log_files:
$(detect_log_files)
EOF
chmod 600 "$CONFIG_FILE"

info "Writing systemd unit"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Usalp Monitoring Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/.venv/bin/python ${INSTALL_DIR}/main.py --config ${CONFIG_FILE}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
Environment=PYTHONPATH=${INSTALL_DIR}
Environment=LOG_LEVEL=INFO

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"
sleep 2

if systemctl is-active --quiet "$SERVICE_NAME"; then
  info "Usalp Agent is running"
  echo "Status: sudo ${BASH_SOURCE[0]} --status"
  echo "Logs:   journalctl -u ${SERVICE_NAME} -f"
else
  warn "Agent service did not start"
  journalctl -u "$SERVICE_NAME" -n 30 --no-pager || true
  exit 1
fi
